from header_common import *
from header_operations import *
from header_parties import *
from header_items import *
from header_skills import *
from header_triggers import *
from header_troops import *
from header_music import *

from module_constants import *

####################################################################################################################
# Simple triggers are the alternative to old style triggers. They do not preserve state, and thus simpler to maintain.
#
#  Each simple trigger contains the following fields:
# 1) Check interval: How frequently this trigger will be checked
# 2) Operation block: This must be a valid operation block. See header_operations.py for reference. 
####################################################################################################################



simple_triggers = [
	(6.0,
		[
			(try_for_range, ":faction", "fac_kingdom_1", "fac_undeads"),
				(faction_get_slot, ":faction_28", ":faction", 28),
				(le, ":faction_28", 0),
				(faction_set_slot, ":faction", slot_faction_state, 1),
			(try_end),
			(call_script, "script_temp_save_number11_initialize"),
			(try_for_range, ":party", "p_pyongyang", "p_place_end"),
				(store_faction_of_party, ":faction_of_party_party", ":party"),
				(faction_slot_eq, ":faction_of_party_party", slot_faction_player_alarm, 1),
				(faction_slot_eq, ":faction_of_party_party", slot_faction_state, 1),
				(party_get_battle_opponent, ":battle_opponent_party", ":party"),
				(try_begin),
					(lt, ":battle_opponent_party", 0),
				(else_try),
					(faction_set_slot, ":faction_of_party_party", slot_faction_state, ":party"),
					(try_begin),
						(ge, ":faction_of_party_party", "fac_kingdom_1"),
						(this_or_next|eq, ":faction_of_party_party", "$contract_fac"),
						(eq, ":faction_of_party_party", "$wm_player_fac"),
						(str_store_party_name, 1, ":party"),
						(display_message, "str_under_attackk", 0x00ffff00),
						(party_relocate_near_party, "p_defence_target", ":party", 0),
						(party_set_flags, "p_defence_target", 256, 0),
						(party_set_icon, "p_defence_target", "icon_defence_target"),
					(try_end),
				(try_end),
			(try_end),
			(assign, ":value", "$wm_player_fac"),
			(try_begin),
				(gt, "$contract_time", 0),
				(is_between, "$contract_fac", "fac_kingdom_1", "fac_kingdoms_end"),
				(neg|troop_slot_ge, "trp_player", 18, 11),
				(assign, ":value", "$contract_fac"),
			(try_end),
			(try_begin),
				(is_between, ":value", "fac_kingdom_1", "fac_kingdoms_end"),
				(faction_get_slot, ":wm_player_fac_state", "$wm_player_fac", slot_faction_state),
				(neg|is_between, ":wm_player_fac_state", "p_pyongyang", "p_place_end"),
				(party_set_flags, "p_defence_target", 256, 1),
			(try_end),
			(try_begin),
				(is_between, ":value", "fac_kingdom_1", "fac_kingdoms_end"),
				(faction_get_slot, ":wm_player_fac_number_of_parties", "$wm_player_fac", slot_faction_number_of_parties),
				(neg|is_between, ":wm_player_fac_number_of_parties", "p_pyongyang", "p_place_end"),
				(party_set_flags, "p_attack_target", 256, 1),
			(try_end),
			(try_begin),
				(neg|is_between, ":value", "fac_kingdom_1", "fac_kingdoms_end"),
				(party_set_flags, "p_defence_target", 256, 1),
				(party_set_flags, "p_attack_target", 256, 1),
			(try_end),
			(try_begin),
				(gt, "$player_recruit_train_start", 0),
				(neg|map_free),
				(is_between, "$g_encountered_party", "p_pyongyang", "p_place_end"),
				(store_party_size_wo_prisoners, reg8, "p_main_party"),
				(party_get_slot, reg9, "p_main_party", slot_town_elder),
				(party_get_slot, reg10, "p_main_party", slot_center_player_relation),
				(display_message, "str_main_party_reportt"),
			(try_end)
		]),

	(2.0,
		[
			(try_begin),
				(this_or_next|eq, "$main_q_step", 13),
				(eq, "$main_q_step", 84),
				(try_begin),
					(eq, "$main_q_faction", "p_ruin_dummy_4"),
					(party_get_position, 11, "p_main_party"),
					(party_get_position, 12, "$main_q_faction"),
					(get_distance_between_positions, ":distance_between_positions_11_12", 11, 12),
					(try_begin),
						(lt, ":distance_between_positions_11_12", 300),
						(party_set_flags, "p_ruin_dummy_4", 256, 0),
						(party_set_flags, "p_ruin_dummy_4", 524288, 0),
						(party_set_flags, "p_ruin_dummy_4", 16384, 1),
						(party_set_icon, "p_ruin_dummy_4", "icon_wm_town_arab_2"),
						(display_message, "str_found_something", 0x0000ff00),
						(play_sound, "snd_found_something"),
						(val_add, "$main_q_step", 1),
					(try_end),
				(try_end),
				(try_begin),
					(eq, "$main_q_faction", "p_ruin_dummy_2"),
					(party_get_position, 11, "p_main_party"),
					(party_get_position, 12, "$main_q_faction"),
					(get_distance_between_positions, ":distance_between_positions_11_12", 11, 12),
					(try_begin),
						(lt, ":distance_between_positions_11_12", 300),
						(party_set_flags, "p_ruin_dummy_2", 256, 0),
						(party_set_flags, "p_ruin_dummy_2", 524288, 0),
						(party_set_flags, "p_ruin_dummy_2", 16384, 1),
						(party_set_icon, "p_ruin_dummy_2", "icon_house_exn"),
						(display_message, "str_found_something", 0x0000ff00),
						(play_sound, "snd_found_something"),
						(val_add, "$main_q_step", 1),
					(try_end),
				(try_end),
			(try_end),
			(try_begin),
				(gt, "$ruin_qst_target_num", 0),
				(gt, "$ruin_qst_remain_turn", 0),
				(party_get_position, 11, "p_main_party"),
				(party_get_position, 12, "$ruin_qst_target_num"),
				(get_distance_between_positions, ":distance_between_positions_11_12", 11, 12),
				(try_begin),
					(troop_get_slot, ":player_love_interest_3", "trp_player", slot_troop_love_interest_3),
					(val_mul, ":player_love_interest_3", 70),
					(val_add, ":player_love_interest_3", 100),
				(try_end),
				(try_begin),
					(lt, ":distance_between_positions_11_12", ":player_love_interest_3"),
					(neg|party_slot_ge, "$ruin_qst_target_num", 3, 2),
					(party_set_flags, "$ruin_qst_target_num", 256, 0),
					(party_set_flags, "$ruin_qst_target_num", 16384, 1),
					(party_set_slot, "$ruin_qst_target_num", slot_party_ignore_player_until, 2),
					(display_message, "str_found_something", 0x0000ff00),
					(play_sound, "snd_found_something"),
				(try_end),
			(try_end),
			(try_for_range, ":troop", "trp_tt_lord_01_00", "trp_tt_lord_end"),
				(troop_slot_ge, ":troop", 26, 1),
				(troop_get_slot, ":troop_last_quest", ":troop", slot_troop_last_quest),
				(try_begin),
					(gt, ":troop_last_quest", 0),
					(val_sub, ":troop_last_quest", 1),
					(troop_set_slot, ":troop", slot_troop_last_quest, ":troop_last_quest"),
				(else_try),
					(le, ":troop_last_quest", 0),
					(troop_set_slot, ":troop", slot_troop_last_persuasion_time, 0),
				(try_end),
			(try_end),
			(try_for_range, ":faction", "fac_neutral", "fac_ally_faction_for_slot"),
				(try_for_range, ":number", 1, 76),
					(faction_get_slot, ":faction_number", ":faction", ":number"),
					(gt, ":faction_number", 0),
					(neg|is_between, ":faction_number", "p_temp_party", "p_reserved_5"),
					(neq, ":faction_number", "p_reserved_5"),
					(party_is_active, ":faction_number"),
					(party_slot_eq, ":faction_number", slot_party_type, 4),
					(party_get_battle_opponent, ":battle_opponent_faction_number", ":faction_number"),
					(lt, ":battle_opponent_faction_number", 0),
					(call_script, "script_wm_map_icon_change_trig", ":faction_number"),
					(party_get_slot, ":faction_number_retreat_flag", ":faction_number", slot_party_retreat_flag),
					(store_distance_to_party_from_party, ":distance_between_positions_11_12", ":faction_number", ":faction_number_retreat_flag"),
					(le, ":distance_between_positions_11_12", 1),
					(party_clear, ":faction_number"),
					(remove_party, ":faction_number"),
					(faction_set_slot, ":faction", ":number", 0),
				(try_end),
			(try_end),
			(try_for_range, ":number", 42, 44),
				(troop_get_slot, ":faction_number", "trp_player", ":number"),
				(gt, ":faction_number", 0),
				(neg|is_between, ":faction_number", "p_temp_party", "p_reserved_5"),
				(neq, ":faction_number", "p_reserved_5"),
				(party_is_active, ":faction_number"),
				(party_slot_eq, ":faction_number", slot_party_type, 5),
				(party_get_battle_opponent, ":battle_opponent_faction_number", ":faction_number"),
				(lt, ":battle_opponent_faction_number", 0),
				(call_script, "script_wm_map_icon_change_trig", ":faction_number"),
				(party_get_slot, ":faction_number_retreat_flag", ":faction_number", slot_party_retreat_flag),
				(store_distance_to_party_from_party, ":distance_between_positions_11_12", ":faction_number", ":faction_number_retreat_flag"),
				(le, ":distance_between_positions_11_12", 1),
				(call_script, "script_traders_trade_with_town", ":faction_number", ":faction_number_retreat_flag"),
				(party_get_slot, ":faction_number_town_tavern", ":faction_number", slot_town_tavern),
				(party_get_slot, ":faction_number_town_store", ":faction_number", slot_town_store),
				(try_begin),
					(eq, ":faction_number_retreat_flag", ":faction_number_town_tavern"),
					(call_script, "script_new_party_ai", ":faction_number", 11, ":faction_number_town_store"),
				(else_try),
					(eq, ":faction_number_retreat_flag", ":faction_number_town_store"),
					(call_script, "script_new_party_ai", ":faction_number", 11, ":faction_number_town_tavern"),
				(try_end),
			(try_end),
			(store_random_in_range, ":troop_last_quest", 42, 44),
			(troop_get_slot, ":player_troop_last_quest", "trp_player", ":troop_last_quest"),
			(assign, ":value", 0),
			(try_begin),
				(neq, ":player_troop_last_quest", "p_main_party"),
				(neg|is_between, ":player_troop_last_quest", "p_temp_party", "p_reserved_5"),
				(neq, ":player_troop_last_quest", "p_reserved_5"),
				(party_is_active, ":player_troop_last_quest"),
				(assign, ":value", 1),
			(try_end),
			(try_for_range, ":faction", "fac_commoners", "fac_neutral"),
				(assign, ":var_14", ":faction"),
				(try_for_range, ":number", 0, 76),
					(faction_get_slot, ":var_14_number", ":var_14", ":number"),
					(gt, ":var_14_number", 0),
					(neg|is_between, ":var_14_number", "p_temp_party", "p_reserved_5"),
					(neq, ":var_14_number", "p_reserved_5"),
					(party_is_active, ":var_14_number"),
					(party_slot_eq, ":var_14_number", slot_party_type, 2),
					(party_get_battle_opponent, ":battle_opponent_var_14_number", ":var_14_number"),
					(lt, ":battle_opponent_var_14_number", 0),
					(call_script, "script_wm_map_icon_change_trig", ":var_14_number"),
					(party_get_slot, ":var_14_number_1", ":var_14_number", 1),
					(party_get_slot, ":var_14_number_town_prison", ":var_14_number", slot_town_prison),
					(party_get_slot, ":faction_number_retreat_flag", ":var_14_number", slot_party_retreat_flag),
					(store_party_size_wo_prisoners, ":party_size_wo_prisoners_var_14_number", ":var_14_number"),
					(try_begin),
						(le, ":party_size_wo_prisoners_var_14_number", 80),
						(store_random_in_range, ":random_in_range_0_3", 0, 3),
						(eq, ":random_in_range_0_3", 0),
						(call_script, "script_party_army_size_execute", ":var_14_number", 1, 87),
					(try_end),
					(try_begin),
						(eq, ":var_14_number_1", 3),
						(party_get_slot, ":var_14_number_center_accumulated_tariffs", ":var_14_number", slot_center_accumulated_tariffs),
						(val_add, ":var_14_number_center_accumulated_tariffs", 1),
						(party_set_slot, ":var_14_number", slot_center_accumulated_tariffs, ":var_14_number_center_accumulated_tariffs"),
					(try_end),
					(try_begin),
						(eq, ":var_14_number_1", 3),
						(neg|party_is_active, ":faction_number_retreat_flag"),
						(call_script, "script_new_party_ai", ":var_14_number", 8, ":var_14_number_town_prison"),
					(else_try),
						(eq, ":var_14_number_1", 3),
						(party_get_battle_opponent, ":battle_opponent_faction_number", ":faction_number_retreat_flag"),
						(ge, ":battle_opponent_faction_number", 0),
						(call_script, "script_new_party_ai", ":var_14_number", 8, ":var_14_number_town_prison"),
					(else_try),
						(party_slot_eq, ":faction_number_retreat_flag", slot_party_last_toll_paid_hours, 5),
						(call_script, "script_new_party_ai", ":var_14_number", 8, ":var_14_number_town_prison"),
					(else_try),
						(eq, ":var_14_number_1", 3),
						(party_slot_ge, ":var_14_number", 48, 4),
						(call_script, "script_new_party_ai", ":var_14_number", 6, ":var_14_number_town_prison"),
						(party_set_slot, ":var_14_number", slot_center_accumulated_tariffs, 0),
					(else_try),
						(eq, ":var_14_number_1", 6),
						(store_distance_to_party_from_party, ":distance_between_positions_11_12", ":var_14_number", ":var_14_number_town_prison"),
						(le, ":distance_between_positions_11_12", 4),
						(call_script, "script_new_party_ai", ":var_14_number", 8, ":var_14_number_town_prison"),
					(else_try),
						(neq, ":var_14_number_1", 3),
						(neq, ":var_14_number_1", 6),
						(call_script, "script_party_count_fit_for_battle", ":var_14_number"),
						(assign, ":value_2", reg0),
						(assign, ":value_3", 76),
						(assign, ":value_4", 0),
						(try_for_range, ":faction_2", "fac_neutral", "fac_ally_faction_for_slot"),
							(eq, ":value_4", 0),
							(try_for_range, ":number", 0, ":value_3"),
								(eq, ":value_4", 0),
								(faction_get_slot, ":faction_2_number", ":faction_2", ":number"),
								(try_begin),
									(eq, ":faction_2", "fac_neutral"),
									(eq, ":number", 0),
									(assign, ":faction_2_number", "p_main_party"),
								(else_try),
									(eq, ":value", 1),
									(eq, ":number", 0),
									(assign, ":faction_2_number", ":player_troop_last_quest"),
								(else_try),
									(eq, ":number", 0),
									(assign, ":faction_2_number", "p_main_party"),
								(try_end),
								(ge, ":faction_2_number", 0),
								(neg|is_between, ":faction_2_number", "p_temp_party", "p_reserved_5"),
								(neq, ":faction_2_number", "p_reserved_5"),
								(party_is_active, ":faction_2_number"),
								(party_slot_eq, ":faction_2_number", slot_party_last_toll_paid_hours, 0),
								(assign, ":value_5", 0),
								(try_begin),
									(neq, ":number", 0),
									(party_slot_eq, ":faction_2_number", slot_party_type, 4),
									(party_get_battle_opponent, ":battle_opponent_faction_2_number", ":faction_2_number"),
									(lt, ":battle_opponent_faction_2_number", 0),
									(assign, ":value_5", 1),
								(else_try),
									(eq, ":number", 0),
									(assign, ":value_5", 1),
								(try_end),
								(eq, ":value_5", 1),
								(call_script, "script_party_count_fit_for_battle", ":faction_2_number"),
								(assign, ":value_6", reg0),
								(ge, ":value_2", ":value_6"),
								(store_distance_to_party_from_party, ":distance_between_positions_11_12", ":var_14_number", ":faction_2_number"),
								(le, ":distance_between_positions_11_12", "$encount_dist"),
								(call_script, "script_new_party_ai", ":var_14_number", 3, ":faction_2_number"),
								(assign, ":value_4", 1),
								(store_add, ":value_3", ":number", 1),
							(try_end),
						(try_end),
					(try_end),
				(try_end),
			(try_end),
			(try_for_range, ":number", 0, 29),
				(faction_get_slot, ":var_14_number", "fac_hot_points", ":number"),
				(gt, ":var_14_number", 0),
				(neg|is_between, ":var_14_number", "p_temp_party", "p_reserved_5"),
				(neq, ":var_14_number", "p_reserved_5"),
				(party_is_active, ":var_14_number"),
				(party_slot_eq, ":var_14_number", slot_party_type, 3),
				(party_get_battle_opponent, ":battle_opponent_var_14_number", ":var_14_number"),
				(lt, ":battle_opponent_var_14_number", 0),
				(call_script, "script_wm_map_icon_change_trig", ":var_14_number"),
				(store_party_size_wo_prisoners, ":party_size_wo_prisoners_var_14_number", ":var_14_number"),
				(try_begin),
					(le, ":party_size_wo_prisoners_var_14_number", 80),
					(store_random_in_range, ":random_in_range_0_3", 0, 3),
					(eq, ":random_in_range_0_3", 0),
					(call_script, "script_party_army_size_execute", ":var_14_number", 1, 87),
				(try_end),
				(party_get_slot, ":var_14_number_1", ":var_14_number", 1),
				(party_get_slot, ":var_14_number_town_prison", ":var_14_number", slot_town_prison),
				(party_get_slot, ":faction_number_retreat_flag", ":var_14_number", slot_party_retreat_flag),
				(party_get_current_terrain, ":current_terrain_var_14_number", ":var_14_number"),
				(try_begin),
					(eq, ":var_14_number_1", 3),
					(party_get_slot, ":var_14_number_center_accumulated_tariffs", ":var_14_number", slot_center_accumulated_tariffs),
					(val_add, ":var_14_number_center_accumulated_tariffs", 1),
					(party_set_slot, ":var_14_number", slot_center_accumulated_tariffs, ":var_14_number_center_accumulated_tariffs"),
				(try_end),
				(try_begin),
					(neq, ":current_terrain_var_14_number", 7),
					(neq, ":current_terrain_var_14_number", 2),
					(call_script, "script_new_party_ai", ":var_14_number", 6, ":var_14_number_town_prison"),
				(else_try),
					(eq, ":var_14_number_1", 3),
					(neg|party_is_active, ":faction_number_retreat_flag"),
					(call_script, "script_new_party_ai", ":var_14_number", 8, ":var_14_number_town_prison"),
				(else_try),
					(eq, ":var_14_number_1", 3),
					(party_get_battle_opponent, ":battle_opponent_faction_number", ":faction_number_retreat_flag"),
					(ge, ":battle_opponent_faction_number", 0),
					(call_script, "script_new_party_ai", ":var_14_number", 8, ":var_14_number_town_prison"),
				(else_try),
					(eq, ":var_14_number_1", 3),
					(party_slot_ge, ":var_14_number", 48, 4),
					(call_script, "script_new_party_ai", ":var_14_number", 6, ":var_14_number_town_prison"),
					(party_set_slot, ":var_14_number", slot_center_accumulated_tariffs, 0),
				(else_try),
					(eq, ":var_14_number_1", 6),
					(store_distance_to_party_from_party, ":distance_between_positions_11_12", ":var_14_number", ":var_14_number_town_prison"),
					(le, ":distance_between_positions_11_12", 4),
					(call_script, "script_new_party_ai", ":var_14_number", 8, ":var_14_number_town_prison"),
				(else_try),
					(neq, ":var_14_number_1", 3),
					(neq, ":var_14_number_1", 6),
					(call_script, "script_party_count_fit_for_battle", ":var_14_number"),
					(assign, ":value_2", reg0),
					(assign, ":value_3", 76),
					(assign, ":value_4", 0),
					(try_for_range, ":faction_2", "fac_neutral", "fac_ally_faction_for_slot"),
						(eq, ":value_4", 0),
						(try_for_range, ":number", 0, ":value_3"),
							(eq, ":value_4", 0),
							(faction_get_slot, ":faction_2_number", ":faction_2", ":number"),
							(try_begin),
								(eq, ":faction_2", "fac_neutral"),
								(eq, ":number", 0),
								(assign, ":faction_2_number", "p_main_party"),
							(else_try),
								(eq, ":value", 1),
								(eq, ":number", 0),
								(assign, ":faction_2_number", ":player_troop_last_quest"),
							(else_try),
								(eq, ":number", 0),
								(assign, ":faction_2_number", "p_main_party"),
							(try_end),
							(ge, ":faction_2_number", 0),
							(neg|is_between, ":faction_2_number", "p_temp_party", "p_reserved_5"),
							(neq, ":faction_2_number", "p_reserved_5"),
							(party_is_active, ":faction_2_number"),
							(party_slot_eq, ":faction_2_number", slot_party_last_toll_paid_hours, 0),
							(assign, ":value_5", 0),
							(try_begin),
								(neq, ":number", 0),
								(party_slot_eq, ":faction_2_number", slot_party_type, 4),
								(party_get_battle_opponent, ":battle_opponent_faction_2_number", ":faction_2_number"),
								(lt, ":battle_opponent_faction_2_number", 0),
								(assign, ":value_5", 1),
							(else_try),
								(eq, ":number", 0),
								(assign, ":value_5", 1),
							(try_end),
							(eq, ":value_5", 1),
							(call_script, "script_party_count_fit_for_battle", ":faction_2_number"),
							(assign, ":value_6", reg0),
							(ge, ":value_2", ":value_6"),
							(store_distance_to_party_from_party, ":distance_between_positions_11_12", ":var_14_number", ":faction_2_number"),
							(le, ":distance_between_positions_11_12", "$encount_dist"),
							(call_script, "script_new_party_ai", ":var_14_number", 3, ":faction_2_number"),
							(assign, ":value_4", 1),
							(store_add, ":value_3", ":number", 1),
						(try_end),
					(try_end),
				(try_end),
			(try_end),
			(try_begin),
				(eq, "$main_q_step", 1),
				(display_message, "str_mq_camp_menu_tip_ala", 0x00ffff00),
			(else_try),
				(eq, "$main_q_step", 2),
				(neg|is_between, "$rt_marked_target", "p_pyongyang", "p_place_end"),
				(display_message, "str_mq_camp_menu_tip_ala", 0x00ffff00),
			(try_end)
		]),

	(1.0,
		[
			(try_begin),
				(neq, "$camera_focus_on", 0),
				(set_camera_follow_party, "p_main_party"),
				(assign, "$camera_focus_on", 0),
			(try_end),
			(try_begin),
				(is_currently_night),
				(assign, "$battle_join_dist", 1),
			(else_try),
				(assign, "$battle_join_dist", 3),
			(try_end),
			(call_script, "script_faction_army_list_scan"),
			(try_begin),
				(ge, "$hourr_count", 24),
				(assign, "$hourr_count", 1),
			(else_try),
				(val_add, "$hourr_count", 1),
			(try_end),
			(try_begin),
				(gt, "$wm_buying_drink_for_army", 0),
				(val_sub, "$wm_buying_drink_for_army", 1),
			(try_end),
			(try_begin),
				(gt, "$attemp_commu", 0),
				(val_sub, "$attemp_commu", 1),
			(try_end),
			(try_begin),
				(gt, "$bet_already", 0),
				(val_sub, "$bet_already", 1),
			(try_end),
			(try_begin),
				(gt, "$innocent_pay", 0),
				(val_sub, "$innocent_pay", 1),
			(try_end),
			(try_begin),
				(eq, "$dayy_count", 2),
				(eq, "$hourr_count", 16),
				(try_begin),
					(eq, "$weekk_count", 2),
					(eq, "$adult_content", 1),
					(troop_slot_eq, "trp_player", slot_troop_last_persuasion_time, 1),
					(call_script, "script_troop_type_sett", "trp_player"),
					(gt, "$troop_gender_type", 10),
					(call_script, "script_adv_exp_diff", 150, 87),
					(display_message, "str_virgin_adv_bonus", 0x00ff9000),
				(try_end),
				(try_begin),
					(eq, "$r_player_class", 3),
					(call_script, "script_wm_honor_change_diff", "trp_player", 1, 87),
					(display_message, "str_lord_honor_bonus", 0x00ff9000),
				(try_end),
			(try_end),
			(try_begin),
				(eq, "$trade_guild_info_on", 1),
				(assign, "$trade_guild_info_on", 0),
				(display_message, "str_trade_info_end", 0x00ff9000),
			(try_end),
			(try_begin),
				(eq, "$hourr_count", 13),
				(store_party_size_wo_prisoners, ":party_size_wo_prisoners_main_party", "p_main_party"),
				(try_begin),
					(ge, ":party_size_wo_prisoners_main_party", 10),
					(val_div, ":party_size_wo_prisoners_main_party", 5),
					(party_get_slot, ":main_party_center_siege_with_belfry", "p_main_party", slot_center_siege_with_belfry),
					(try_begin),
						(lt, ":main_party_center_siege_with_belfry", ":party_size_wo_prisoners_main_party"),
						(display_message, "str_food_loww", 0x00ff0000),
						(call_script, "script_party_food_level_diff", "p_main_party", ":party_size_wo_prisoners_main_party", 34),
						(call_script, "script_moral_level_diff", "p_main_party", -50),
						(call_script, "script_wm_after_battle_health_result"),
					(else_try),
						(call_script, "script_party_food_level_diff", "p_main_party", ":party_size_wo_prisoners_main_party", 34),
					(try_end),
				(try_end),
				(party_get_slot, ":main_party_center_player_relation", "p_main_party", slot_center_player_relation),
				(try_begin),
					(lt, ":main_party_center_player_relation", 45),
					(call_script, "script_party_army_size_execute", "p_main_party", 85, 3),
					(call_script, "script_stack_kill_sc", 15, 0, 2, 1),
					(display_message, "str_moral_loww", 0x00ff0000),
				(try_end),
			(try_end),
			(call_script, "script_player_fix_army_size"),
			(try_begin),
				(map_free),
				(assign, "$player_recruit_train_start", 0),
				(neg|party_slot_eq, "p_main_party", slot_party_last_toll_paid_hours, 0),
				(party_set_slot, "p_main_party", slot_party_last_toll_paid_hours, 0),
			(try_end),
			(try_begin),
				(gt, "$player_recruit_train_start", 0),
				(try_begin),
					(neg|map_free),
					(is_between, "$g_encountered_party", "p_pyongyang", "p_place_end"),
					(store_faction_of_party, ":faction_of_party_g_encountered_party", "$g_encountered_party"),
					(assign, ":value", "$wm_player_fac"),
					(assign, ":value_2", "$g_encountered_party"),
					(assign, ":value_3", "p_main_party"),
					(try_begin),
						(neg|party_slot_eq, ":value_3", slot_party_last_toll_paid_hours, 5),
						(party_set_slot, ":value_3", slot_party_last_toll_paid_hours, 5),
					(try_end),
					(store_party_size_wo_prisoners, ":party_size_wo_prisoners_value_3", ":value_3"),
					(party_get_slot, ":value_2_town_alley", ":value_2", slot_town_alley),
					(try_begin),
						(lt, ":value_2_town_alley", 10),
						(assign, ":value_2_town_alley", 10),
					(try_end),
					(val_mul, ":value_2_town_alley", 160),
					(val_div, ":value_2_town_alley", 100),
					(call_script, "script_moral_level_diff", ":value_3", 1),
					(try_begin),
						(eq, "$player_recruit_train_start", 2),
						(try_begin),
							(ge, ":party_size_wo_prisoners_value_3", 1000),
							(store_div, ":value_4", ":party_size_wo_prisoners_value_3", 1000),
						(else_try),
							(assign, ":value_4", 5),
						(try_end),
						(call_script, "script_party_money_level_ge", "p_main_party", ":value_4"),
						(try_begin),
							(eq, "$hourr_count", 12),
							(eq, "$wm_mo_continue", 1),
							(call_script, "script_exp_reward_for_common_troop", 1),
							(call_script, "script_party_money_level_diff", ":value_3", ":value_4", 34),
							(val_mul, ":value_4", 24),
							(assign, reg8, ":value_4"),
							(display_message, "str_traincostreg8"),
						(else_try),
							(eq, "$wm_mo_continue", 1),
							(call_script, "script_exp_reward_for_common_troop", 1),
							(call_script, "script_party_money_level_dif_no_mes", ":value_3", ":value_4", 34),
						(else_try),
							(neq, "$wm_mo_continue", 1),
							(eq, "$hourr_count", 12),
							(display_message, "str_nomoney", 0x00ff0000),
						(try_end),
						(call_script, "script_train_level_diff", ":value_3", 1),
					(try_end),
					(try_begin),
						(neq, ":faction_of_party_g_encountered_party", "$wm_player_fac"),
						(val_mul, ":value_2_town_alley", 40),
						(val_div, ":value_2_town_alley", 100),
						(try_begin),
							(eq, "$player_recruit_train_start", 1),
							(eq, "$hourr_count", 14),
							(display_message, "str_recruit_quarter", 0x00ffff00),
						(try_end),
					(else_try),
						(neg|party_slot_eq, "$g_encountered_party", slot_town_tavern, "trp_player"),
						(val_mul, ":value_2_town_alley", 66),
						(val_div, ":value_2_town_alley", 100),
						(try_begin),
							(eq, "$player_recruit_train_start", 1),
							(eq, "$hourr_count", 14),
							(display_message, "str_recruit_half", 0x00ffff00),
						(try_end),
					(try_end),
					(try_begin),
						(eq, "$player_recruit_train_start", 1),
						(try_begin),
							(lt, ":party_size_wo_prisoners_value_3", 500),
							(assign, ":value_2_town_alley", 500),
							(assign, ":value_5", 500),
							(try_begin),
								(call_script, "script_party_money_level_ge", "p_main_party", ":value_5"),
								(eq, "$wm_mo_continue", 1),
								(dialog_box, "str_recruit_regular_army", "str_box_note"),
							(try_end),
						(else_try),
							(store_div, ":value_5", ":value_2_town_alley", 2),
						(try_end),
						(call_script, "script_party_money_level_ge", "p_main_party", ":value_5"),
						(store_party_size_wo_prisoners, ":party_size_wo_prisoners_main_party_2", "p_main_party"),
						(try_begin),
							(eq, "$hourr_count", 12),
							(eq, "$wm_mo_continue", 1),
							(call_script, "script_party_army_size_execute", ":value_3", ":value_2_town_alley", 87),
							(store_party_size_wo_prisoners, ":party_size_wo_prisoners_main_party_3", "p_main_party"),
							(neq, ":party_size_wo_prisoners_main_party_2", ":party_size_wo_prisoners_main_party_3"),
							(store_party_size_wo_prisoners, ":party_size_wo_prisoners_value_2", ":value_2"),
							(try_begin),
								(gt, ":party_size_wo_prisoners_value_2", 10000),
								(call_script, "script_party_army_size_execute", ":value_2", ":value_2_town_alley", 34),
							(try_end),
							(call_script, "script_party_money_level_diff", ":value_3", ":value_5", 34),
							(val_mul, ":value_5", 24),
							(assign, reg8, ":value_5"),
							(display_message, "str_recruitcostreg8"),
						(else_try),
							(eq, "$wm_mo_continue", 1),
							(call_script, "script_party_army_size_execute", ":value_3", ":value_2_town_alley", 87),
							(store_party_size_wo_prisoners, ":party_size_wo_prisoners_main_party_3", "p_main_party"),
							(neq, ":party_size_wo_prisoners_main_party_2", ":party_size_wo_prisoners_main_party_3"),
							(store_party_size_wo_prisoners, ":party_size_wo_prisoners_value_2", ":value_2"),
							(try_begin),
								(gt, ":party_size_wo_prisoners_value_2", 8000),
								(call_script, "script_party_army_size_execute", ":value_2", ":value_2_town_alley", 34),
							(try_end),
							(call_script, "script_party_money_level_dif_no_mes", ":value_3", ":value_5", 34),
						(else_try),
							(neq, "$wm_mo_continue", 1),
							(eq, "$hourr_count", 12),
							(display_message, "str_nomoney", 0x00ff0000),
						(try_end),
					(try_end),
					(call_script, "script_party_food_level_dif_no_mes", ":value_3", 20000, 87),
				(try_end),
			(try_end),
			(try_begin),
				(is_between, "$ply_staying_party_no", "p_pyongyang", "p_place_end"),
				(eq, "$ply_staying_army_recruit_on", 1),
				(assign, ":value_2", "$ply_staying_party_no"),
				(troop_get_slot, ":player_betrothed", "trp_player", slot_troop_betrothed),
				(val_clamp, ":player_betrothed", 0, 7),
				(store_mul, ":value_6", ":player_betrothed", 500),
				(store_mul, ":value_7", 100, 70),
				(val_add, ":value_7", ":value_6"),
				(lt, "$ply_staying_army_size", ":value_7"),
				(party_get_slot, ":value_2_town_alley", ":value_2", slot_town_alley),
				(store_faction_of_party, ":faction_of_party_g_encountered_party", ":value_2"),
				(try_begin),
					(neq, ":faction_of_party_g_encountered_party", "$wm_player_fac"),
					(val_mul, ":value_2_town_alley", 40),
					(val_div, ":value_2_town_alley", 100),
				(else_try),
					(neg|party_slot_eq, ":value_2", slot_town_tavern, "trp_player"),
					(val_mul, ":value_2_town_alley", 66),
					(val_div, ":value_2_town_alley", 100),
				(try_end),
				(store_div, ":value_5", ":value_2_town_alley", 2),
				(call_script, "script_party_money_level_ge", "p_main_party", ":value_5"),
				(eq, "$wm_mo_continue", 1),
				(assign, ":var_18", "$ply_staying_army_size"),
				(val_add, "$ply_staying_army_size", ":value_2_town_alley"),
				(try_begin),
					(gt, "$ply_staying_army_size", ":value_7"),
					(assign, "$ply_staying_army_size", ":value_7"),
				(try_end),
				(neq, ":var_18", "$ply_staying_army_size"),
				(store_party_size_wo_prisoners, ":party_size_wo_prisoners_value_2", ":value_2"),
				(try_begin),
					(gt, ":party_size_wo_prisoners_value_2", 10000),
					(call_script, "script_party_army_size_execute", ":value_2", ":value_2_town_alley", 34),
				(try_end),
				(call_script, "script_party_money_level_dif_no_mes", "p_main_party", ":value_5", 34),
			(try_end),
			(try_begin),
				(eq, "$hourr_count", 15),
				(call_script, "script_common_prisoner_escape"),
				(store_random_in_range, "$disaster_occur_time", 1, 25),
			(try_end),
			(try_begin),
				(eq, "$hourr_count", "$disaster_occur_time"),
				(party_get_current_terrain, ":current_terrain_main_party", "p_main_party"),
				(store_random_in_range, ":random_in_range_0_20", 0, 20),
				(try_begin),
					(eq, ":current_terrain_main_party", 4),
					(eq, ":random_in_range_0_20", 0),
					(neq, "$wm_player_fac", "fac_kingdom_7"),
					(neq, "$wm_player_fac", "fac_kingdom_10"),
					(neq, "$wm_player_fac", "fac_kingdom_12"),
					(neq, "$wm_player_fac", "fac_kingdom_16"),
					(neq, "$wm_player_fac", "fac_kingdom_29"),
					(neq, "$wm_player_fac", "fac_kingdom_30"),
					(neq, "$wm_player_fac", "fac_kingdom_47"),
					(neq, "$wm_player_fac", "fac_kingdom_48"),
					(neq, "$wm_player_fac", "fac_kingdom_50"),
					(neq, "$wm_player_fac", "fac_kingdom_52"),
					(neq, "$wm_player_fac", "fac_kingdom_53"),
					(neq, "$wm_player_fac", "fac_kingdom_54"),
					(party_relocate_near_party, "p_disaster_ice_ply", "p_main_party", 0),
					(party_set_flags, "p_disaster_ice_ply", 256, 0),
					(str_store_party_name, 11, "p_main_party"),
					(display_message, "str_disaster_coldbringer", 0x00ff0000),
					(play_sound, "snd_Typhoon"),
					(assign, "$ply_timer_fall_disaster", 24),
					(troop_get_slot, ":player_love_interest_1", "trp_player", slot_troop_love_interest_1),
					(store_random_in_range, ":random_in_range_0_7", 0, 7),
					(try_begin),
						(lt, ":random_in_range_0_7", ":player_love_interest_1"),
						(display_message, "str_logistics_avoid", 0x0000ff00),
					(else_try),
						(call_script, "script_party_army_size_execute", "p_main_party", 75, 3),
						(call_script, "script_moral_level_diff", "p_main_party", -30),
						(call_script, "script_wm_after_battle_health_result"),
						(call_script, "script_stack_kill_sc", 25, 0, 1, 1),
					(try_end),
				(else_try),
					(eq, ":current_terrain_main_party", 5),
					(eq, ":random_in_range_0_20", 0),
					(neq, "$wm_player_fac", "fac_kingdom_2"),
					(neq, "$wm_player_fac", "fac_kingdom_3"),
					(neq, "$wm_player_fac", "fac_kingdom_4"),
					(neq, "$wm_player_fac", "fac_kingdom_6"),
					(neq, "$wm_player_fac", "fac_kingdom_9"),
					(neq, "$wm_player_fac", "fac_kingdom_13"),
					(neq, "$wm_player_fac", "fac_kingdom_14"),
					(neq, "$wm_player_fac", "fac_kingdom_21"),
					(neq, "$wm_player_fac", "fac_kingdom_22"),
					(neq, "$wm_player_fac", "fac_kingdom_30"),
					(neq, "$wm_player_fac", "fac_kingdom_31"),
					(neq, "$wm_player_fac", "fac_kingdom_32"),
					(neq, "$wm_player_fac", "fac_kingdom_34"),
					(neq, "$wm_player_fac", "fac_kingdom_40"),
					(neq, "$wm_player_fac", "fac_kingdom_41"),
					(neq, "$wm_player_fac", "fac_kingdom_44"),
					(neq, "$wm_player_fac", "fac_kingdom_49"),
					(neq, "$wm_player_fac", "fac_kingdom_51"),
					(neq, "$wm_player_fac", "fac_kingdom_52"),
					(neq, "$wm_player_fac", "fac_africa_people"),
					(neq, "$wm_player_fac", "fac_hindu_people"),
					(neq, "$wm_player_fac", "fac_arabian_people"),
					(party_relocate_near_party, "p_disaster_sand_ply", "p_main_party", 0),
					(party_set_flags, "p_disaster_sand_ply", 256, 0),
					(str_store_party_name, 11, "p_main_party"),
					(display_message, "str_disaster_sand_storm", 0x00ff0000),
					(play_sound, "snd_Typhoon"),
					(assign, "$ply_timer_fall_disaster", 24),
					(troop_get_slot, ":player_love_interest_1", "trp_player", slot_troop_love_interest_1),
					(store_random_in_range, ":random_in_range_0_7", 0, 7),
					(try_begin),
						(lt, ":random_in_range_0_7", ":player_love_interest_1"),
						(display_message, "str_logistics_avoid", 0x0000ff00),
					(else_try),
						(call_script, "script_party_army_size_execute", "p_main_party", 85, 3),
						(call_script, "script_moral_level_diff", "p_main_party", -30),
						(call_script, "script_wm_after_battle_health_result"),
						(call_script, "script_stack_kill_sc", 15, 0, 1, 1),
					(try_end),
				(else_try),
					(this_or_next|eq, ":current_terrain_main_party", 7),
					(eq, ":current_terrain_main_party", 2),
					(eq, ":random_in_range_0_20", 0),
					(party_relocate_near_party, "p_disaster_storm_ply", "p_main_party", 0),
					(party_set_flags, "p_disaster_storm_ply", 256, 0),
					(str_store_party_name, 11, "p_main_party"),
					(display_message, "str_disaster_storm", 0x00ff0000),
					(play_sound, "snd_Flood"),
					(assign, "$ply_timer_fall_disaster", 24),
					(troop_get_slot, ":player_love_interest_1", "trp_player", slot_troop_love_interest_1),
					(store_random_in_range, ":random_in_range_0_7", 0, 7),
					(try_begin),
						(call_script, "script_wm_main_party_has_troop_sc", "trp_npc1"),
						(eq, "$wm_comp_continue", 1),
						(display_message, "str_disaster_storm_alonso", 0x0000ff00),
					(else_try),
						(lt, ":random_in_range_0_7", ":player_love_interest_1"),
						(display_message, "str_navigation_avoid", 0x0000ff00),
					(else_try),
						(call_script, "script_party_army_size_execute", "p_main_party", 60, 3),
						(call_script, "script_moral_level_diff", "p_main_party", -35),
						(call_script, "script_wm_after_battle_health_result"),
						(call_script, "script_stack_kill_sc", 40, 0, 1, 1),
					(try_end),
				(try_end),
			(try_end),
			(try_begin),
				(gt, "$ply_timer_fall_disaster", 0),
				(val_sub, "$ply_timer_fall_disaster", 1),
			(else_try),
				(eq, "$ply_timer_fall_disaster", 0),
				(party_set_flags, "p_disaster_storm_ply", 256, 1),
				(party_set_flags, "p_disaster_sand_ply", 256, 1),
				(party_set_flags, "p_disaster_ice_ply", 256, 1),
			(try_end),
			(call_script, "script_morale_train_event", "p_main_party"),
			(try_for_range, ":value", "fac_kingdom_1", "fac_undeads"),
				(faction_slot_eq, ":value", slot_faction_player_alarm, 1),
				(try_for_range, ":number", 56, 76),
					(faction_get_slot, ":value_3", ":value", ":number"),
					(gt, ":value_3", 0),
					(neg|is_between, ":value_3", "p_temp_party", "p_reserved_5"),
					(neq, ":value_3", "p_reserved_5"),
					(party_is_active, ":value_3"),
					(party_slot_eq, ":value_3", slot_party_type, 1),
					(call_script, "script_wm_map_icon_change_trig", ":value_3"),
					(party_get_battle_opponent, ":battle_opponent_value_3", ":value_3"),
					(try_begin),
						(lt, ":battle_opponent_value_3", 0),
						(call_script, "script_morale_train_event", ":value_3"),
					(try_end),
					(try_begin),
						(lt, ":battle_opponent_value_3", 0),
						(store_random_in_range, ":random_in_range_0_20", 0, 300),
						(try_begin),
							(eq, ":random_in_range_0_20", 0),
							(call_script, "script_ai_suffer_storm", ":value_3", 1, ":value"),
						(else_try),
							(eq, ":random_in_range_0_20", 1),
							(call_script, "script_ai_suffer_storm", ":value_3", 2, ":value"),
						(else_try),
							(eq, ":random_in_range_0_20", 2),
							(call_script, "script_ai_suffer_storm", ":value_3", 3, ":value"),
						(try_end),
					(try_end),
					(call_script, "script_party_count_fit_for_battle", ":value_3"),
					(assign, ":var_25", reg0),
					(faction_get_slot, ":value_28", ":value", 28),
					(faction_get_slot, ":value_number_of_parties", ":value", slot_faction_number_of_parties),
					(faction_get_slot, ":value_state", ":value", slot_faction_state),
					(party_get_slot, ":value_3_1", ":value_3", 1),
					(party_get_slot, ":value_3_town_prosperity", ":value_3", slot_town_prosperity),
					(party_get_slot, ":value_3_retreat_flag", ":value_3", slot_party_retreat_flag),
					(party_get_slot, ":value_3_town_prison", ":value_3", slot_town_prison),
					(store_faction_of_party, ":faction_of_party_value_3_town_prison", ":value_3_town_prison"),
					(try_begin),
						(neq, ":faction_of_party_value_3_town_prison", ":value"),
						(call_script, "script_home_land_sett_retry", ":value_3", ":value"),
						(party_get_slot, ":value_3_town_prison", ":value_3", slot_town_prison),
					(else_try),
						(neg|is_between, ":value_3_town_prison", "p_pyongyang", "p_place_end"),
						(call_script, "script_home_land_sett_retry", ":value_3", ":value"),
						(party_get_slot, ":value_3_town_prison", ":value_3", slot_town_prison),
					(try_end),
					(assign, ":value_8", 0),
					(try_begin),
						(is_between, ":value_3_town_prison", "p_pyongyang", "p_place_end"),
						(store_faction_of_party, ":faction_of_party_value_3_town_prison", ":value_3_town_prison"),
						(eq, ":faction_of_party_value_3_town_prison", ":value"),
						(assign, ":value_8", 1),
					(try_end),
					(store_mul, ":value_7", 100, 70),
					(party_stack_get_troop_id, ":party_stack_troop_id_value_3_0", ":value_3", 0),
					(try_begin),
						(is_between, ":party_stack_troop_id_value_3_0", "trp_tt_lord_01_00", "trp_tt_lord_end"),
						(troop_get_slot, ":player_betrothed", ":party_stack_troop_id_value_3_0", slot_troop_betrothed),
						(val_clamp, ":player_betrothed", 0, 7),
						(store_mul, ":value_6", ":player_betrothed", 500),
						(val_add, ":value_7", ":value_6"),
					(try_end),
					(party_get_slot, ":value_3_last_toll_paid_hours", ":value_3", slot_party_last_toll_paid_hours),
					(party_get_attached_to, ":attached_to_value_3", ":value_3"),
					(assign, ":value_2", 0),
					(try_begin),
						(is_between, ":attached_to_value_3", "p_pyongyang", "p_place_end"),
						(assign, ":value_2", ":attached_to_value_3"),
						(try_begin),
							(neq, ":value_3_last_toll_paid_hours", 5),
							(party_set_slot, ":value_3", slot_party_last_toll_paid_hours, 5),
						(try_end),
					(else_try),
						(neq, ":value_3_last_toll_paid_hours", 0),
						(party_set_slot, ":value_3", slot_party_last_toll_paid_hours, 0),
					(try_end),
					(party_get_slot, ":value_3_center_accumulated_tariffs", ":value_3", slot_center_accumulated_tariffs),
					(try_begin),
						(eq, ":value_3_1", 3),
						(val_add, ":value_3_center_accumulated_tariffs", 1),
						(party_set_slot, ":value_3", slot_center_accumulated_tariffs, ":value_3_center_accumulated_tariffs"),
					(try_end),
					(assign, ":value_9", 0),
					(assign, ":value_10", 1),
					(try_begin),
						(le, ":value_28", 0),
						(eq, ":value_2", 0),
						(gt, ":value_3_town_prosperity", 0),
						(eq, ":value_8", 1),
						(call_script, "script_new_party_ai", ":value_3", 6, ":value_3_town_prison"),
					(else_try),
						(neg|is_between, ":value_3_retreat_flag", "p_temp_party", "p_reserved_5"),
						(neq, ":value_3_retreat_flag", "p_reserved_5"),
						(party_is_active, ":value_3_retreat_flag"),
						(party_slot_eq, ":value_3_retreat_flag", slot_party_last_toll_paid_hours, 5),
						(eq, ":value_8", 1),
						(call_script, "script_new_party_ai", ":value_3", 6, ":value_3_town_prison"),
					(else_try),
						(party_slot_ge, ":value_3", 48, 4),
						(eq, ":value_8", 1),
						(call_script, "script_new_party_ai", ":value_3", 6, ":value_3_town_prison"),
						(party_set_slot, ":value_3", slot_center_accumulated_tariffs, 0),
						(assign, ":value_9", 1),
					(else_try),
						(gt, ":var_25", 2100),
						(eq, ":value_2", 0),
						(neq, ":value_3_1", 6),
						(lt, ":battle_opponent_value_3", 0),
						(faction_set_slot, "fac_player_supporters_faction", slot_faction_village_walker_female_troop, "p_main_party"),
						(assign, ":var_41", "fac_player_supporters_faction"),
						(assign, ":value_11", "fac_undeads"),
						(try_for_range, ":var_43", ":var_41", ":value_11"),
							(eq, ":value_10", 1),
							(store_relation, ":relation_value_var_43", ":value", ":var_43"),
							(lt, ":relation_value_var_43", 0),
							(assign, ":value_12", 76),
							(try_for_range, ":localvariable", 56, ":value_12"),
								(faction_get_slot, ":var_43_localvariable", ":var_43", ":localvariable"),
								(try_begin),
									(this_or_next|eq, ":var_43", "fac_kingdoms_end"),
									(eq, ":var_43", "fac_player_supporters_faction"),
									(assign, ":var_43_localvariable", "p_main_party"),
								(try_end),
								(ge, ":var_43_localvariable", 0),
								(neg|is_between, ":var_43_localvariable", "p_temp_party", "p_reserved_5"),
								(neq, ":var_43_localvariable", "p_reserved_5"),
								(party_is_active, ":var_43_localvariable"),
								(party_slot_eq, ":var_43_localvariable", slot_party_last_toll_paid_hours, 0),
								(store_distance_to_party_from_party, ":distance_to_party_from_party_value_3_var_43_localvariable", ":value_3", ":var_43_localvariable"),
								(le, ":distance_to_party_from_party_value_3_var_43_localvariable", "$encount_dist"),
								(call_script, "script_party_count_fit_for_battle", ":var_43_localvariable"),
								(assign, ":var_49", reg0),
								(set_show_messages, 0),
								(store_mul, ":value_13", ":var_49", 75),
								(val_div, ":value_13", 100),
								(set_show_messages, 1),
								(store_random_in_range, ":random_in_range_0_10", 0, 10),
								(try_begin),
									(ge, ":var_25", ":var_49"),
									(call_script, "script_new_party_ai", ":value_3", 3, ":var_43_localvariable"),
									(assign, ":value_10", 0),
									(assign, ":value_11", ":var_43"),
									(val_add, ":value_11", 1),
									(assign, ":value_12", ":localvariable"),
									(val_add, ":value_12", 1),
									(assign, ":value_9", 1),
								(else_try),
									(is_between, ":var_25", ":value_13", ":var_49"),
									(lt, ":random_in_range_0_10", 5),
									(call_script, "script_new_party_ai", ":value_3", 3, ":var_43_localvariable"),
									(assign, ":value_10", 0),
									(assign, ":value_11", ":var_43"),
									(val_add, ":value_11", 1),
									(assign, ":value_12", ":localvariable"),
									(val_add, ":value_12", 1),
									(assign, ":value_9", 1),
								(else_try),
									(call_script, "script_new_party_ai", ":value_3", 10, ":var_43_localvariable"),
									(assign, ":value_10", 0),
									(assign, ":value_11", ":var_43"),
									(val_add, ":value_11", 1),
									(assign, ":value_12", ":localvariable"),
									(val_add, ":value_12", 1),
									(assign, ":value_9", 1),
								(try_end),
							(try_end),
						(try_end),
					(try_end),
					(store_random_in_range, ":random_in_range_0_7", 0, 8),
					(party_get_slot, ":value_3_retreat_flag", ":value_3", slot_party_retreat_flag),
					(assign, ":value_14", 0),
					(try_begin),
						(party_is_active, ":value_3_retreat_flag"),
						(assign, ":value_14", 1),
					(try_end),
					(try_begin),
						(eq, ":value_9", 0),
						(try_begin),
							(is_between, ":value_state", "p_pyongyang", "p_place_end"),
							(gt, ":value_2", 0),
							(eq, ":value_2", ":value_state"),
							(party_get_slot, ":value_2_town_alley", ":value_2", slot_town_alley),
							(party_stack_get_troop_id, ":party_stack_troop_id_value_3_0", ":value_3", 0),
							(try_begin),
								(neg|party_slot_eq, ":value_2", slot_town_tavern, ":party_stack_troop_id_value_3_0"),
								(val_div, ":value_2_town_alley", 2),
							(try_end),
							(call_script, "script_moral_level_diff", ":value_3", 1),
							(call_script, "script_train_level_diff", ":value_3", 1),
							(call_script, "script_party_army_size_execute", ":value_3", ":value_2_town_alley", 87),
							(store_party_size_wo_prisoners, ":party_size_wo_prisoners_value_2", ":value_2"),
							(try_begin),
								(gt, ":party_size_wo_prisoners_value_2", 8000),
								(call_script, "script_party_army_size_execute", ":value_2", ":value_2_town_alley", 34),
							(try_end),
							(call_script, "script_party_food_level_diff", ":value_3", 20000, 87),
							(party_set_slot, ":value_3", slot_town_prosperity, 0),
						(else_try),
							(eq, ":value_3_1", 2),
							(gt, ":var_25", 3000),
							(is_between, ":value_number_of_parties", "p_pyongyang", "p_place_end"),
							(store_faction_of_party, ":faction_of_party_g_encountered_party", ":value_number_of_parties"),
							(store_relation, ":relation_value_var_43", ":faction_of_party_g_encountered_party", ":value"),
							(lt, ":relation_value_var_43", 0),
							(store_distance_to_party_from_party, ":distance_to_party_from_party_value_3_var_43_localvariable", ":value_3", ":value_number_of_parties"),
							(le, ":distance_to_party_from_party_value_3_var_43_localvariable", 2),
							(call_script, "script_party_count_fit_for_battle", ":value_3"),
							(assign, ":var_53", reg0),
							(call_script, "script_party_count_fit_for_battle", ":value_number_of_parties"),
							(assign, ":var_54", reg0),
							(try_begin),
								(gt, ":value_28", 0),
								(try_for_parties, ":var_55"),
									(neq, ":var_55", "p_main_party"),
									(neg|is_between, ":var_55", "p_temp_party", "p_reserved_5"),
									(neq, ":var_55", "p_reserved_5"),
									(party_is_active, ":var_55"),
									(party_slot_eq, ":var_55", slot_party_type, 1),
									(store_faction_of_party, ":faction_of_party_var_55", ":var_55"),
									(store_relation, ":relation_faction_of_party_g_encountered_party_faction_of_party_var_55", ":faction_of_party_g_encountered_party", ":faction_of_party_var_55"),
									(try_begin),
										(lt, ":relation_faction_of_party_g_encountered_party_faction_of_party_var_55", 0),
										(store_distance_to_party_from_party, ":distance_to_party_from_party_var_55_value_number_of_parties", ":var_55", ":value_number_of_parties"),
										(le, ":distance_to_party_from_party_var_55_value_number_of_parties", 6),
										(call_script, "script_party_count_fit_for_battle", ":var_55"),
										(val_add, ":var_53", reg0),
									(try_end),
									(try_begin),
										(ge, ":relation_faction_of_party_g_encountered_party_faction_of_party_var_55", 0),
										(store_distance_to_party_from_party, ":distance_to_party_from_party_var_55_value_number_of_parties", ":var_55", ":value_number_of_parties"),
										(le, ":distance_to_party_from_party_var_55_value_number_of_parties", 6),
										(call_script, "script_party_count_fit_for_battle", ":var_55"),
										(val_add, ":var_54", reg0),
									(try_end),
								(try_end),
							(else_try),
								(try_for_range, ":number", 56, 76),
									(faction_get_slot, ":value_number", ":value", ":number"),
									(ge, ":value_number", 0),
									(neg|is_between, ":value_number", "p_temp_party", "p_reserved_5"),
									(neq, ":value_number", "p_reserved_5"),
									(party_is_active, ":value_number"),
									(store_distance_to_party_from_party, ":distance_to_party_from_party_value_3_var_43_localvariable", ":value_number", ":value_number_of_parties"),
									(le, ":distance_to_party_from_party_value_3_var_43_localvariable", 6),
									(call_script, "script_party_count_fit_for_battle", ":value_number"),
									(val_add, ":var_53", reg0),
								(try_end),
								(try_for_range, ":number", 56, 76),
									(faction_get_slot, ":faction_of_party_g_encountered_party_number", ":faction_of_party_g_encountered_party", ":number"),
									(ge, ":faction_of_party_g_encountered_party_number", 0),
									(neg|is_between, ":faction_of_party_g_encountered_party_number", "p_temp_party", "p_reserved_5"),
									(neq, ":faction_of_party_g_encountered_party_number", "p_reserved_5"),
									(party_is_active, ":faction_of_party_g_encountered_party_number"),
									(store_distance_to_party_from_party, ":distance_to_party_from_party_value_3_var_43_localvariable", ":faction_of_party_g_encountered_party_number", ":value_number_of_parties"),
									(le, ":distance_to_party_from_party_value_3_var_43_localvariable", 6),
									(call_script, "script_party_count_fit_for_battle", ":faction_of_party_g_encountered_party_number"),
									(val_add, ":var_54", reg0),
								(try_end),
								(call_script, "script_party_count_fit_for_battle", ":value_number_of_parties"),
								(val_add, ":var_54", reg0),
							(try_end),
							(try_begin),
								(gt, ":var_53", ":var_54"),
								(call_script, "script_new_party_ai", ":value_3", 9, ":value_number_of_parties"),
							(else_try),
								(call_script, "script_new_party_ai", ":value_3", 0, ":value_number_of_parties"),
							(try_end),
						(else_try),
							(lt, ":battle_opponent_value_3", 0),
							(gt, ":value_2", 0),
							(ge, ":var_25", ":value_7"),
							(party_detach, ":value_3"),
							(call_script, "script_new_party_ai", ":value_3", 0, ":value_2"),
						(else_try),
							(lt, ":battle_opponent_value_3", 0),
							(gt, ":value_2", 0),
							(party_get_slot, ":value_3_center_accumulated_rents", ":value_3", slot_center_accumulated_rents),
							(try_begin),
								(ge, ":value_3_center_accumulated_rents", 48),
								(heal_party, ":value_3"),
							(else_try),
								(val_add, ":value_3_center_accumulated_rents", 1),
								(party_set_slot, ":value_3", slot_center_accumulated_rents, ":value_3_center_accumulated_rents"),
							(try_end),
							(party_get_slot, ":value_2_town_alley", ":value_2", slot_town_alley),
							(party_stack_get_troop_id, ":party_stack_troop_id_value_3_0", ":value_3", 0),
							(try_begin),
								(neg|party_slot_eq, ":value_2", slot_town_tavern, ":party_stack_troop_id_value_3_0"),
								(val_div, ":value_2_town_alley", 2),
							(try_end),
							(call_script, "script_moral_level_diff", ":value_3", 1),
							(call_script, "script_train_level_diff", ":value_3", 1),
							(call_script, "script_party_army_size_execute", ":value_3", ":value_2_town_alley", 87),
							(store_party_size_wo_prisoners, ":party_size_wo_prisoners_value_2", ":value_2"),
							(try_begin),
								(gt, ":party_size_wo_prisoners_value_2", 10000),
								(call_script, "script_party_army_size_execute", ":value_2", ":value_2_town_alley", 34),
							(try_end),
							(call_script, "script_party_food_level_diff", ":value_3", 20000, 87),
							(party_set_slot, ":value_3", slot_town_prosperity, 0),
						(else_try),
							(lt, ":battle_opponent_value_3", 0),
							(this_or_next|eq, ":value_3_1", 6),
							(eq, ":value_3_1", 5),
							(is_between, ":value_3_retreat_flag", "p_pyongyang", "p_place_end"),
							(eq, ":value_14", 1),
							(store_faction_of_party, ":faction_of_party_g_encountered_party", ":value_3_retreat_flag"),
							(eq, ":faction_of_party_g_encountered_party", ":value"),
							(store_distance_to_party_from_party, ":distance_to_party_from_party_value_3_var_43_localvariable", ":value_3", ":value_3_retreat_flag"),
							(le, ":distance_to_party_from_party_value_3_var_43_localvariable", 2),
							(party_set_slot, ":value_3", slot_center_accumulated_rents, 0),
							(party_attach_to_party, ":value_3", ":value_3_retreat_flag"),
							(call_script, "script_new_party_ai", ":value_3", 7, 0),
						(else_try),
							(gt, ":var_25", 6000),
							(eq, ":value_3_1", 6),
							(eq, ":value_8", 1),
							(call_script, "script_new_party_ai", ":value_3", 0, ":value_3_town_prison"),
						(else_try),
							(le, ":var_25", 3000),
							(eq, ":value_8", 1),
							(call_script, "script_new_party_ai", ":value_3", 6, ":value_3_town_prison"),
						(else_try),
							(lt, ":battle_opponent_value_3", 0),
							(is_between, ":value_state", "p_pyongyang", "p_place_end"),
							(store_faction_of_party, ":faction_of_party_g_encountered_party", ":value_state"),
							(store_relation, ":relation_value_faction_of_party_g_encountered_party", ":value", ":faction_of_party_g_encountered_party"),
							(ge, ":relation_value_faction_of_party_g_encountered_party", 0),
							(call_script, "script_new_party_ai", ":value_3", 5, ":value_state"),
						(else_try),
							(lt, ":battle_opponent_value_3", 0),
							(is_between, ":value_number_of_parties", "p_pyongyang", "p_place_end"),
							(store_faction_of_party, ":faction_of_party_g_encountered_party", ":value_number_of_parties"),
							(store_relation, ":relation_value_var_43", ":faction_of_party_g_encountered_party", ":value"),
							(lt, ":relation_value_var_43", 0),
							(call_script, "script_new_party_ai", ":value_3", 2, ":value_number_of_parties"),
						(else_try),
							(eq, ":random_in_range_0_7", 0),
							(lt, ":battle_opponent_value_3", 0),
							(lt, ":var_25", 7000),
							(neq, ":value_3_1", 2),
							(neq, ":value_3_1", 5),
							(eq, ":value_8", 1),
							(call_script, "script_new_party_ai", ":value_3", 6, ":value_3_town_prison"),
						(else_try),
							(eq, ":value_3_1", 10),
							(lt, ":battle_opponent_value_3", 0),
							(eq, ":value_14", 1),
							(store_distance_to_party_from_party, ":distance_to_party_from_party_value_3_var_43_localvariable", ":value_3", ":value_3_retreat_flag"),
							(gt, ":distance_to_party_from_party_value_3_var_43_localvariable", "$encount_dist"),
							(eq, ":value_8", 1),
							(call_script, "script_new_party_ai", ":value_3", 8, ":value_3_town_prison"),
						(else_try),
							(eq, ":value_3_1", 3),
							(eq, ":value_14", 1),
							(store_faction_of_party, ":faction_of_party_value_3_retreat_flag", ":value_3_retreat_flag"),
							(store_relation, ":relation_value_faction_of_party_g_encountered_party", ":value", ":faction_of_party_value_3_retreat_flag"),
							(ge, ":relation_value_faction_of_party_g_encountered_party", 0),
							(eq, ":value_8", 1),
							(call_script, "script_new_party_ai", ":value_3", 0, ":value_3_town_prison"),
						(else_try),
							(eq, ":value_3_1", 3),
							(lt, ":battle_opponent_value_3", 0),
							(eq, ":value_14", 0),
							(eq, ":value_8", 1),
							(call_script, "script_new_party_ai", ":value_3", 0, ":value_3_town_prison"),
						(else_try),
							(eq, ":value_3_1", 3),
							(lt, ":battle_opponent_value_3", 0),
							(eq, ":value_14", 1),
							(store_distance_to_party_from_party, ":distance_to_party_from_party_value_3_var_43_localvariable", ":value_3", ":value_3_retreat_flag"),
							(gt, ":distance_to_party_from_party_value_3_var_43_localvariable", "$encount_dist"),
							(eq, ":value_8", 1),
							(call_script, "script_new_party_ai", ":value_3", 0, ":value_3_town_prison"),
						(else_try),
							(lt, ":battle_opponent_value_3", 0),
							(eq, ":value_8", 1),
							(call_script, "script_new_party_ai", ":value_3", 0, ":value_3_town_prison"),
						(else_try),
							(lt, ":battle_opponent_value_3", 0),
							(call_script, "script_new_party_ai", ":value_3", 0, ":value_3"),
						(try_end),
					(try_end),
				(try_end),
			(try_end),
			(try_begin),
				(le, "$wm_popup_menu_id", 0),
				(le, "$molda_start_map_conversation", 0),
				(assign, ":value_15", 0),
				(try_begin),
					(neq, "$hourr_count", 19),
					(try_begin),
						(lt, "$main_q_step", 1),
						(assign, ":value_15", 1),
					(else_try),
						(eq, "$main_q_step", 3),
						(le, "$main_q_day", 0),
						(assign, ":value_15", 1),
					(else_try),
						(eq, "$main_q_step", 19),
						(le, "$main_q_day", 0),
						(call_script, "script_main_quest_cla_req", 0),
						(assign, ":value_16", reg11),
						(ge, ":value_16", 1),
						(assign, ":value_15", 1),
					(else_try),
						(eq, "$main_q_step", 25),
						(le, "$main_q_day", 0),
						(call_script, "script_main_quest_cla_req", 0),
						(assign, ":value_16", reg11),
						(ge, ":value_16", 2),
						(assign, ":value_15", 1),
					(else_try),
						(eq, "$main_q_step", 26),
						(le, "$main_q_day", 0),
						(assign, ":value_15", 1),
					(else_try),
						(eq, "$main_q_step", 28),
						(le, "$main_q_day", 0),
						(call_script, "script_main_quest_cla_req", 0),
						(assign, ":value_16", reg11),
						(ge, ":value_16", 3),
						(assign, ":value_15", 1),
					(else_try),
						(eq, "$main_q_step", 33),
						(le, "$main_q_day", 0),
						(call_script, "script_main_quest_cla_req", 0),
						(assign, ":value_16", reg11),
						(ge, ":value_16", 4),
						(assign, ":value_15", 1),
					(else_try),
						(eq, "$main_q_step", 37),
						(le, "$main_q_day", 0),
						(assign, ":value_15", 1),
					(else_try),
						(eq, "$main_q_step", 38),
						(le, "$main_q_day", 0),
						(assign, ":value_15", 1),
					(else_try),
						(eq, "$main_q_step", 42),
						(le, "$main_q_day", 0),
						(call_script, "script_main_quest_cla_req", 0),
						(assign, ":value_16", reg11),
						(ge, ":value_16", 5),
						(assign, ":value_15", 1),
					(else_try),
						(eq, "$main_q_step", 45),
						(le, "$main_q_day", 0),
						(call_script, "script_main_quest_cla_req", 0),
						(assign, ":value_16", reg11),
						(ge, ":value_16", 6),
						(assign, ":value_15", 1),
					(else_try),
						(eq, "$main_q_step", 49),
						(le, "$main_q_day", 0),
						(call_script, "script_main_quest_cla_req", 0),
						(assign, ":value_16", reg11),
						(ge, ":value_16", 7),
						(assign, ":value_15", 1),
					(else_try),
						(eq, "$main_q_step", 51),
						(le, "$main_q_day", 0),
						(assign, ":value_15", 1),
					(else_try),
						(eq, "$main_q_step", 56),
						(le, "$main_q_day", 0),
						(call_script, "script_main_quest_cla_req", 0),
						(assign, ":value_16", reg11),
						(ge, ":value_16", 8),
						(assign, ":value_15", 1),
					(else_try),
						(eq, "$main_q_step", 57),
						(le, "$main_q_day", 0),
						(assign, ":value_15", 1),
					(else_try),
						(eq, "$main_q_step", 61),
						(le, "$main_q_day", 0),
						(assign, ":value_15", 1),
					(else_try),
						(eq, "$main_q_step", 66),
						(le, "$main_q_day", 0),
						(call_script, "script_main_quest_cla_req", 0),
						(assign, ":value_16", reg11),
						(ge, ":value_16", 9),
						(assign, ":value_15", 1),
					(else_try),
						(eq, "$main_q_step", 69),
						(le, "$main_q_day", 0),
						(assign, ":value_15", 1),
					(else_try),
						(eq, "$main_q_step", 70),
						(le, "$main_q_day", 0),
						(assign, ":value_15", 1),
					(else_try),
						(eq, "$main_q_step", 71),
						(le, "$main_q_day", 0),
						(call_script, "script_main_quest_cla_req", 0),
						(assign, ":value_16", reg11),
						(ge, ":value_16", 10),
						(assign, ":value_15", 1),
					(else_try),
						(eq, "$main_q_step", 72),
						(le, "$main_q_day", 0),
						(assign, ":value_15", 1),
					(else_try),
						(eq, "$main_q_step", 76),
						(le, "$main_q_day", 0),
						(call_script, "script_main_quest_cla_req", 0),
						(assign, ":value_16", reg11),
						(ge, ":value_16", 11),
						(assign, ":value_15", 1),
					(else_try),
						(eq, "$main_q_step", 81),
						(le, "$main_q_day", 0),
						(call_script, "script_main_quest_cla_req", 0),
						(assign, ":value_16", reg11),
						(ge, ":value_16", 12),
						(assign, ":value_15", 1),
					(else_try),
						(eq, "$main_q_step", 87),
						(is_between, "$main_q_troop", "trp_tt_lord_01_00", "trp_tt_lord_end"),
						(is_between, "$main_q_faction", "trp_tt_lord_01_00", "trp_tt_lord_end"),
						(assign, ":value_15", 1),
					(else_try),
						(eq, "$main_q_step", 93),
						(le, "$main_q_day", 0),
						(call_script, "script_main_quest_cla_req", 0),
						(assign, ":value_16", reg11),
						(ge, ":value_16", 13),
						(assign, ":value_15", 1),
					(try_end),
					(try_begin),
						(eq, ":value_15", 1),
						(party_get_current_terrain, ":current_terrain_main_party", "p_main_party"),
						(this_or_next|eq, ":current_terrain_main_party", 7),
						(eq, ":current_terrain_main_party", 2),
						(assign, ":value_15", 0),
					(try_end),
				(try_end),
				(try_begin),
					(neq, "$hourr_count", 19),
					(eq, ":value_15", 1),
					(jump_to_menu, "mnu_main_quest_menu"),
				(else_try),
					(gt, "$need_meeting_loose", 0),
					(eq, "$meeting_popup_auto", 1),
					(neq, "$hourr_count", 19),
					(call_script, "script_attend_to_national_conference"),
				(else_try),
					(neq, "$hourr_count", 19),
					(store_random_in_range, ":random_in_range_0_2000", 0, 2000),
					(eq, ":random_in_range_0_2000", 0),
					(call_script, "script_wm_random_event_in_move"),
				(else_try),
					(eq, "$hourr_count", 19),
					(try_begin),
						(eq, "$dark_quest_we_know", 2),
						(jump_to_menu, "mnu_we_know_assassination"),
						(assign, "$dark_quest_we_know", 0),
					(else_try),
						(eq, "$dark_quest_we_know", 1),
						(jump_to_menu, "mnu_mess_we_know"),
						(assign, "$dark_quest_we_know", 2),
					(else_try),
						(eq, "$dayy_count", 6),
						(eq, "$pirate_king", 0),
						(assign, ":var_67", 0),
						(try_for_range, ":troop", "trp_ex_npc_020", "trp_ex_npc_054"),
							(troop_get_slot, ":troop_last_persuasion_time", ":troop", slot_troop_last_persuasion_time),
							(val_add, ":var_67", ":troop_last_persuasion_time"),
						(try_end),
						(try_begin),
							(ge, ":var_67", 87),
							(assign, "$pirate_king", 1),
							(jump_to_menu, "mnu_pirate_king"),
						(try_end),
					(try_end),
				(try_end),
			(try_end),
			(call_script, "script_wm_map_icon_change_trig", "p_main_party"),
			(assign, ":value_3", "p_main_party"),
			(assign, ":var_70", 5000),
			(try_begin),
				(try_begin),
					(eq, "$r_player_class", 5),
					(party_set_slot, "p_main_party", slot_center_last_visited_by_lord, 0),
				(else_try),
					(eq, "$r_player_class", 3),
					(party_set_slot, "p_main_party", slot_village_smoke_added, 0),
				(try_end),
				(val_div, ":var_70", 5),
				(store_add, ":value_17", 42, 1),
				(try_for_range, ":localvariable_2", 30, ":value_17"),
					(party_get_slot, ":value_3_localvariable_2", ":value_3", ":localvariable_2"),
					(try_begin),
						(gt, ":value_3_localvariable_2", ":var_70"),
						(party_set_slot, ":value_3", ":localvariable_2", ":var_70"),
					(try_end),
				(try_end),
			(try_end),
			(try_begin),
				(eq, "$r_player_class", 5),
				(party_set_slot, "p_main_party", slot_center_last_visited_by_lord, 1000),
			(else_try),
				(eq, "$r_player_class", 3),
				(party_set_slot, "p_main_party", slot_village_smoke_added, 1000),
			(try_end)
		]),

]